name: rugpt
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - python>=3.6,<3.7
  - pip
  - pytorch>=1.3
  - cuda100 
  - tensorboard
  - nvidia-apex
  - pip:
    - nltk>=3.4
    - numpy>=1.15.4
    - pandas>=0.24.0
    - sentencepiece>=0.1.8
    - tensorflow>=1.12.0
    - boto3==1.11.11
    - regex==2020.1.8
    - transformers==2.8.0
    - tensorflow-cpu
    - fastai>=2
#    - torch-blocksparse
